CREATE PROCEDURE CRE_USER_PR 
(
	@P_IDENTIFICACION INT,
	@P_NOMBRE NVARCHAR(20),
	@P_APELLIDO1 NVARCHAR(20),
	@P_APELLIDO2 NVARCHAR(20),
	@P_CORREO VARCHAR(50),
	@P_TELEFONO INT,
	@P_FECHA_NACIMIENTO DATE,
	@P_FOTO_PERFIL NVARCHAR(250),
	@P_CONTRASENA NVARCHAR(10),
	@P_ROL_ID INT
)

AS
BEGIN
	INSERT INTO tblUser(Created, Updated, Identificacion, Nombre, Apellido1, Apellido2, Correo, Telefono, FechaNacimiento, FotoPerfil, Contrasena, RolId)
	VALUES(GETDATE(), NULL, @P_IDENTIFICACION, @P_NOMBRE, @P_APELLIDO1, @P_APELLIDO2, @P_CORREO, @P_TELEFONO, @P_FECHA_NACIMIENTO, @P_FOTO_PERFIL, @P_CONTRASENA, @P_ROL_ID);
END
GO