CREATE PROCEDURE UPD_USER_PROFILE_PR
(
	@P_ID INT,
	@P_IDENTIFICACION INT,
	@P_NOMBRE NVARCHAR(20),
	@P_APELLIDO1 NVARCHAR(20),
	@P_APELLIDO2 NVARCHAR(20),
	@P_CORREO VARCHAR(50),
	@P_TELEFONO INT,
	@P_FECHA_NACIMIENTO DATE,
	@P_FOTO_PERFIL NVARCHAR(250)
)
AS
BEGIN
	UPDATE tblUser
	SET Updated = GETDATE(),
	    Identificacion = @P_IDENTIFICACION,
	    Nombre = @P_NOMBRE,
	    Apellido1 = @P_APELLIDO1,
	    Apellido2 = @P_APELLIDO2,
	    Correo = @P_CORREO,
	    Telefono = @P_TELEFONO,
	    FechaNacimiento = @P_FECHA_NACIMIENTO,
	    FotoPerfil = @P_FOTO_PERFIL
	WHERE Id = @P_ID;
END
GO