<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.12" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entities-DTOs\Entities-DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DB Scripts\MantenimientoScripts\" />
    <Folder Include="DB Scripts\CorteEnergia\" />
    <Folder Include="DB Scripts\AlmacenCentralScripts\" />
  </ItemGroup>

</Project>
